In [1]:
x = "jack"

In [2]:
x

'jack'

In [3]:
x = "krish"

In [4]:
x

'krish'

In [5]:
db = [1,"Raj","ok"] # multiple things in one single variable

In [6]:
type(db)

list

In [7]:
db[1]

'Raj'

In [8]:
db.append(1111)

In [9]:
db

[1, 'Raj', 'ok', 1111]

In [10]:
# slicing operator
db[1:2]

['Raj']

In [11]:
db[:]

[1, 'Raj', 'ok', 1111]

In [12]:
db[-1]

1111

In [13]:
db[-3:]

['Raj', 'ok', 1111]

In [14]:
db = [[1,'Raj',1111,'ok'],
      [2,'yash',2222,'vgood'],
      [3,'ram',3333,'ok'],
      [4,'abhi',4444,'good']]

In [15]:
db

[[1, 'Raj', 1111, 'ok'],
 [2, 'yash', 2222, 'vgood'],
 [3, 'ram', 3333, 'ok'],
 [4, 'abhi', 4444, 'good']]

In [16]:
type(db)

list

In [17]:
db[1]

[2, 'yash', 2222, 'vgood']

In [18]:
db[1:4]

[[2, 'yash', 2222, 'vgood'], [3, 'ram', 3333, 'ok'], [4, 'abhi', 4444, 'good']]

In [19]:
db[2][2]

3333

In [20]:
import numpy as np

In [21]:
a = np.array(db)

In [22]:
type(a)

numpy.ndarray

In [23]:
a

array([['1', 'Raj', '1111', 'ok'],
       ['2', 'yash', '2222', 'vgood'],
       ['3', 'ram', '3333', 'ok'],
       ['4', 'abhi', '4444', 'good']], dtype='<U11')

In [24]:
a[0]

array(['1', 'Raj', '1111', 'ok'], dtype='<U11')

In [25]:
a[1:4]

array([['2', 'yash', '2222', 'vgood'],
       ['3', 'ram', '3333', 'ok'],
       ['4', 'abhi', '4444', 'good']], dtype='<U11')

In [26]:
a[:] 

array([['1', 'Raj', '1111', 'ok'],
       ['2', 'yash', '2222', 'vgood'],
       ['3', 'ram', '3333', 'ok'],
       ['4', 'abhi', '4444', 'good']], dtype='<U11')

In [27]:
a[1:3:,1:3]

array([['yash', '2222'],
       ['ram', '3333']], dtype='<U11')

In [28]:
a1 = np.array([1,2,3,4,5,6,7,8,])

In [29]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
type(a1)

numpy.ndarray

In [31]:
a1.shape

(8,)

In [32]:
a

array([['1', 'Raj', '1111', 'ok'],
       ['2', 'yash', '2222', 'vgood'],
       ['3', 'ram', '3333', 'ok'],
       ['4', 'abhi', '4444', 'good']], dtype='<U11')

In [33]:
a.shape

(4, 4)

In [34]:
a1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
a.reshape(2,8)

array([['1', 'Raj', '1111', 'ok', '2', 'yash', '2222', 'vgood'],
       ['3', 'ram', '3333', 'ok', '4', 'abhi', '4444', 'good']],
      dtype='<U11')

In [38]:
a1.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [40]:
a1.reshape(8,1).shape

(8, 1)

In [43]:
a1.reshape(-1,1).shape

(8, 1)