In [4]:
import numpy as np
import pandas as pd

In [5]:
ds = pd.read_csv('Salary_Data.csv')

In [6]:
ds.head(5)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [7]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [8]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [9]:
x = ds['YearsExperience'].values.reshape(30,1)

In [10]:
type(x)

numpy.ndarray

In [11]:
x.shape

(30, 1)

In [12]:
y = ds['Salary']

In [13]:
from sklearn.linear_model  import LinearRegression

In [14]:
model = LinearRegression()

In [15]:
model.fit(x,y)

LinearRegression()

In [16]:
model.coef_

array([9449.96232146])

In [17]:
# y = w * x
# w = 9449  x = 1.1
# y = 9449*1.1 = 10393.900000000001
model.predict([[1.1]])

array([36187.15875227])

In [18]:
model.predict([[2.5]])

array([49417.10600231])

In [19]:
36187/39343 * 100 # so we are 91% accurate in predicting salary of a 1.1 yr exp person which is quite close to the actual value

91.97824263528454

In [20]:
9449 * 1.1 # but the value predicted is diff than what we calculate now it is because of bias 

10393.900000000001

In [21]:
c = model.intercept_  # This value is called bias in the ML model
c

25792.20019866871

# so by adding bias if we calculate the value of y we will get it correct
# y = c + wx


In [22]:
y = 25792.20019866871 + 9449.96232146 * 1.1 
y

36187.158752274714

In [23]:
import joblib 

In [24]:
joblib.dump(model,"trained.pk1") # so we have saved the model in a file called "trained.pk1" using the joblib module

['trained.pk1']